SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO A JOIN ITEM_TREE B
ON A.ITEM_ID = B.ITEM_ID
-- 부모 아이템의 ID가 'RARE' 등급인 아이템의 ID 중 하나인 경우만 선택
WHERE B.PARENT_ITEM_ID IN((SELECT C.ITEM_ID
FROM ITEM_INFO C
WHERE RARITY = 'RARE'))
ORDER BY ITEM_ID DESC
;
